// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurneroApi.Data;

#nullable disable

namespace TurneroApi.Migrations
{
  [DbContext(typeof(TurneroDbContext))]
  partial class TurneroDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .UseCollation("utf8mb4_unicode_ci")
          .HasAnnotation("ProductVersion", "8.0.21")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
      MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

      modelBuilder.Entity("TurneroApi.Models.Cliente", b =>
          {
            b.Property<ulong>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

            b.Property<string>("Dni")
                      .IsRequired()
                      .HasMaxLength(10)
                      .HasColumnType("varchar(10)")
                      .HasColumnName("dni");

            b.Property<string>("Titular")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("varchar(50)")
                      .HasColumnName("titular");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Dni")
                      .IsUnique();

            b.ToTable("clientes", null, t =>
                      {
                    t.HasCheckConstraint("ck_clientes_dni", "dni REGEXP '^[0-9]+$'");
                  });
          });

      modelBuilder.Entity("TurneroApi.Models.Contenido", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<bool>("Activo")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("tinyint(1)")
                      .HasDefaultValue(true)
                      .HasColumnName("activo");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Nombre")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)")
                      .HasColumnName("nombre");

            b.Property<string>("Ruta")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("varchar(255)")
                      .HasColumnName("ruta");

            b.Property<string>("Tipo")
                      .IsRequired()
                      .HasColumnType("longtext")
                      .HasColumnName("tipo");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Nombre")
                      .IsUnique();

            b.ToTable("contenidos", null, t =>
                      {
                    t.HasCheckConstraint("ck_contenidos_tipo", "tipo IN ('imagen','video')");
                  });
          });

      modelBuilder.Entity("TurneroApi.Models.Estado", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Descripcion")
                      .IsRequired()
                      .HasMaxLength(20)
                      .HasColumnType("varchar(20)")
                      .HasColumnName("descripcion");

            b.Property<string>("Letra")
                      .IsRequired()
                      .HasMaxLength(2)
                      .HasColumnType("varchar(2)")
                      .HasColumnName("letra");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Letra")
                      .IsUnique();

            b.ToTable("estados", null, t =>
                      {
                    t.HasCheckConstraint("ck_estados_letra", "letra REGEXP '^[A-Z]{1,2}$'");
                  });
          });

      modelBuilder.Entity("TurneroApi.Models.Historial", b =>
          {
            b.Property<ulong>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

            b.Property<string>("Comentarios")
                      .HasMaxLength(255)
                      .HasColumnType("varchar(255)")
                      .HasColumnName("comentarios");

            b.Property<uint>("EstadoId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("estado_id");

            b.Property<DateTime>("Fecha")
                      .HasColumnType("datetime")
                      .HasColumnName("fecha");

            b.Property<uint?>("PuestoId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("puesto_id");

            b.Property<ulong>("TicketId")
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("ticket_id");

            b.Property<ulong?>("TurnoId")
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("turno_id");

            b.Property<uint?>("UsuarioId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("usuario_id");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("EstadoId");

            b.HasIndex("Fecha")
                      .HasDatabaseName("idx_historial_fecha");

            b.HasIndex("PuestoId");

            b.HasIndex("TicketId")
                      .HasDatabaseName("idx_historial_ticket");

            b.HasIndex("TurnoId");

            b.HasIndex("UsuarioId");

            b.ToTable("historiales", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Mostrador", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Ip")
                      .IsRequired()
                      .HasMaxLength(15)
                      .HasColumnType("varchar(15)")
                      .HasColumnName("ip");

            b.Property<uint>("Numero")
                      .HasColumnType("int unsigned")
                      .HasColumnName("numero");

            b.Property<string>("Tipo")
                      .HasMaxLength(10)
                      .HasColumnType("varchar(10)")
                      .HasColumnName("tipo");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Ip")
                      .IsUnique();

            b.HasIndex("Numero", "Ip")
                      .IsUnique();

            b.ToTable("mostradores", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.MostradorSector", b =>
          {
            b.Property<uint>("MostradorId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("mostrador_id");

            b.Property<uint>("SectorId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("sector_id");

            b.HasKey("MostradorId", "SectorId");

            b.HasIndex("SectorId");

            b.ToTable("mostrador_sector", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Permiso", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Descripcion")
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)")
                      .HasColumnName("descripcion");

            b.Property<string>("Nombre")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("varchar(50)")
                      .HasColumnName("nombre");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Nombre")
                      .IsUnique();

            b.ToTable("permisos", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Puesto", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<bool>("Activo")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("tinyint(1)")
                      .HasDefaultValue(true)
                      .HasColumnName("activo");

            b.Property<DateTime?>("Login")
                      .HasColumnType("datetime")
                      .HasColumnName("login");

            b.Property<DateTime?>("Logout")
                      .HasColumnType("datetime")
                      .HasColumnName("logout");

            b.Property<uint>("MostradorId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("mostrador_id");

            b.Property<uint>("UsuarioId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("usuario_id");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("MostradorId");

            b.HasIndex("UsuarioId")
                      .HasDatabaseName("idx_puestos_usuario");

            b.ToTable("puestos", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Rol", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Nombre")
                      .IsRequired()
                      .HasMaxLength(20)
                      .HasColumnType("varchar(20)")
                      .HasColumnName("nombre");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Nombre")
                      .IsUnique();

            b.ToTable("roles", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.RolPermiso", b =>
          {
            b.Property<uint>("RolId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("rol_id");

            b.Property<uint>("PermisoId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("permiso_id");

            b.HasKey("RolId", "PermisoId");

            b.HasIndex("PermisoId");

            b.ToTable("rol_permiso", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Sector", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<bool>("Activo")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("tinyint(1)")
                      .HasDefaultValue(true)
                      .HasColumnName("activo");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Descripcion")
                      .HasMaxLength(120)
                      .HasColumnType("varchar(120)")
                      .HasColumnName("descripcion");

            b.Property<string>("Letra")
                      .HasMaxLength(3)
                      .HasColumnType("varchar(3)")
                      .HasColumnName("letra");

            b.Property<string>("Nombre")
                      .HasMaxLength(50)
                      .HasColumnType("varchar(50)")
                      .HasColumnName("nombre");

            b.Property<uint?>("PadreId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("padre_id");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("Letra")
                      .IsUnique();

            b.HasIndex("Nombre")
                      .IsUnique();

            b.HasIndex("PadreId");

            b.ToTable("sectores", null, t =>
                      {
                    t.HasCheckConstraint("ck_sectores_letra", "letra IS NULL OR letra REGEXP '^[A-Z]{1,3}$'");
                  });
          });

      modelBuilder.Entity("TurneroApi.Models.Ticket", b =>
          {
            b.Property<ulong>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

            b.Property<DateTime?>("Actualizado")
                      .HasColumnType("datetime")
                      .HasColumnName("actualizado");

            b.Property<ulong>("ClienteId")
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("cliente_id");

            b.Property<uint>("EstadoId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("estado_id");

            b.Property<DateTime>("Fecha")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("fecha")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Letra")
                      .IsRequired()
                      .HasMaxLength(2)
                      .HasColumnType("varchar(2)")
                      .HasColumnName("letra");

            b.Property<uint>("Numero")
                      .HasColumnType("int unsigned")
                      .HasColumnName("numero");

            b.Property<uint?>("SectorIdActual")
                      .HasColumnType("int unsigned")
                      .HasColumnName("sector_id_actual");

            b.Property<uint>("SectorIdOrigen")
                      .HasColumnType("int unsigned")
                      .HasColumnName("sector_id_origen");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("ClienteId")
                      .HasDatabaseName("idx_tickets_cliente");

            b.HasIndex("EstadoId");

            b.HasIndex("Fecha")
                      .HasDatabaseName("idx_tickets_fecha");

            b.HasIndex("SectorIdOrigen");

            b.HasIndex("SectorIdActual", "EstadoId")
                      .HasDatabaseName("idx_ticket_sector_estado");

            b.HasIndex("Letra", "Numero", "Fecha")
                      .IsUnique();

            b.ToTable("tickets", null, t =>
                      {
                    t.HasCheckConstraint("ck_tickets_letra", "letra REGEXP '^[A-Z]{1,2}$'");
                  });
          });

      modelBuilder.Entity("TurneroApi.Models.Turno", b =>
          {
            b.Property<ulong>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

            b.Property<uint>("EstadoId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("estado_id");

            b.Property<DateTime?>("FechaFin")
                      .HasColumnType("datetime")
                      .HasColumnName("fecha_fin");

            b.Property<DateTime>("FechaInicio")
                      .HasColumnType("datetime")
                      .HasColumnName("fecha_inicio");

            b.Property<uint>("PuestoId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("puesto_id");

            b.Property<ulong>("TicketId")
                      .HasColumnType("bigint unsigned")
                      .HasColumnName("ticket_id");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("EstadoId");

            b.HasIndex("PuestoId")
                      .HasDatabaseName("idx_turno_puesto");

            b.HasIndex("TicketId")
                      .HasDatabaseName("idx_turnos_ticket");

            b.ToTable("turnos", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Usuario", b =>
          {
            b.Property<uint>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int unsigned")
                      .HasColumnName("id");

            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

            b.Property<bool>("Activo")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("tinyint(1)")
                      .HasDefaultValue(true)
                      .HasColumnName("activo");

            b.Property<string>("Apellido")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("varchar(50)")
                      .HasColumnName("apellido");

            b.Property<DateTime>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("created_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Nombre")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("varchar(50)")
                      .HasColumnName("nombre");

            b.Property<uint>("RolId")
                      .HasColumnType("int unsigned")
                      .HasColumnName("rol_id");

            b.Property<DateTime>("UpdatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("datetime")
                      .HasColumnName("updated_at")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

            b.Property<string>("Username")
                      .IsRequired()
                      .HasMaxLength(30)
                      .HasColumnType("varchar(30)")
                      .HasColumnName("username");

            b.HasKey("Id")
                      .HasName("PRIMARY");

            b.HasIndex("RolId");

            b.HasIndex("Username")
                      .IsUnique();

            b.HasIndex("Nombre", "Apellido")
                      .HasDatabaseName("idx_usuarios_nombre_apellido");

            b.ToTable("usuarios", (string)null);
          });

      modelBuilder.Entity("TurneroApi.Models.Historial", b =>
          {
            b.HasOne("TurneroApi.Models.Estado", "EstadoNavigation")
                      .WithMany("Historiales")
                      .HasForeignKey("EstadoId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Puesto", "PuestoNavigation")
                      .WithMany("Historiales")
                      .HasForeignKey("PuestoId")
                      .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("TurneroApi.Models.Ticket", "TicketNavigation")
                      .WithMany("Historiales")
                      .HasForeignKey("TicketId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Turno", "TurnoNavigation")
                      .WithMany("Historiales")
                      .HasForeignKey("TurnoId")
                      .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("TurneroApi.Models.Usuario", "UsuarioNavigation")
                      .WithMany("Historiales")
                      .HasForeignKey("UsuarioId")
                      .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("EstadoNavigation");

            b.Navigation("PuestoNavigation");

            b.Navigation("TicketNavigation");

            b.Navigation("TurnoNavigation");

            b.Navigation("UsuarioNavigation");
          });

      modelBuilder.Entity("TurneroApi.Models.MostradorSector", b =>
          {
            b.HasOne("TurneroApi.Models.Mostrador", "Mostrador")
                      .WithMany("MostradorSectores")
                      .HasForeignKey("MostradorId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Sector", "Sector")
                      .WithMany("MostradorSectores")
                      .HasForeignKey("SectorId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.Navigation("Mostrador");

            b.Navigation("Sector");
          });

      modelBuilder.Entity("TurneroApi.Models.Puesto", b =>
          {
            b.HasOne("TurneroApi.Models.Mostrador", "MostradorNavigation")
                      .WithMany("Puestos")
                      .HasForeignKey("MostradorId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Usuario", "UsuarioNavigation")
                      .WithMany("Puestos")
                      .HasForeignKey("UsuarioId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.Navigation("MostradorNavigation");

            b.Navigation("UsuarioNavigation");
          });

      modelBuilder.Entity("TurneroApi.Models.RolPermiso", b =>
          {
            b.HasOne("TurneroApi.Models.Permiso", "Permiso")
                      .WithMany("RolPermisos")
                      .HasForeignKey("PermisoId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Rol", "Rol")
                      .WithMany("RolPermisos")
                      .HasForeignKey("RolId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.Navigation("Permiso");

            b.Navigation("Rol");
          });

      modelBuilder.Entity("TurneroApi.Models.Sector", b =>
          {
            b.HasOne("TurneroApi.Models.Sector", "Padre")
                      .WithMany("InversePadre")
                      .HasForeignKey("PadreId")
                      .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("Padre");
          });

      modelBuilder.Entity("TurneroApi.Models.Ticket", b =>
          {
            b.HasOne("TurneroApi.Models.Cliente", "ClienteNavigation")
                      .WithMany("Tickets")
                      .HasForeignKey("ClienteId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Estado", "EstadoNavigation")
                      .WithMany("Tickets")
                      .HasForeignKey("EstadoId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Sector", "SectorIdActualNavigation")
                      .WithMany("TicketsSectorIdActualNavigation")
                      .HasForeignKey("SectorIdActual")
                      .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("TurneroApi.Models.Sector", "SectorIdOrigenNavigation")
                      .WithMany("TicketsSectorIdOrigenNavigation")
                      .HasForeignKey("SectorIdOrigen")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.Navigation("ClienteNavigation");

            b.Navigation("EstadoNavigation");

            b.Navigation("SectorIdActualNavigation");

            b.Navigation("SectorIdOrigenNavigation");
          });

      modelBuilder.Entity("TurneroApi.Models.Turno", b =>
          {
            b.HasOne("TurneroApi.Models.Estado", "EstadoNavigation")
                      .WithMany("Turnos")
                      .HasForeignKey("EstadoId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Puesto", "PuestoNavigation")
                      .WithMany("Turnos")
                      .HasForeignKey("PuestoId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.HasOne("TurneroApi.Models.Ticket", "TicketNavigation")
                      .WithMany("Turnos")
                      .HasForeignKey("TicketId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.Navigation("EstadoNavigation");

            b.Navigation("PuestoNavigation");

            b.Navigation("TicketNavigation");
          });

      modelBuilder.Entity("TurneroApi.Models.Usuario", b =>
          {
            b.HasOne("TurneroApi.Models.Rol", "RolNavigation")
                      .WithMany("Usuarios")
                      .HasForeignKey("RolId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired();

            b.Navigation("RolNavigation");
          });

      modelBuilder.Entity("TurneroApi.Models.Cliente", b =>
          {
            b.Navigation("Tickets");
          });

      modelBuilder.Entity("TurneroApi.Models.Estado", b =>
          {
            b.Navigation("Historiales");

            b.Navigation("Tickets");

            b.Navigation("Turnos");
          });

      modelBuilder.Entity("TurneroApi.Models.Mostrador", b =>
          {
            b.Navigation("MostradorSectores");

            b.Navigation("Puestos");
          });

      modelBuilder.Entity("TurneroApi.Models.Permiso", b =>
          {
            b.Navigation("RolPermisos");
          });

      modelBuilder.Entity("TurneroApi.Models.Puesto", b =>
          {
            b.Navigation("Historiales");

            b.Navigation("Turnos");
          });

      modelBuilder.Entity("TurneroApi.Models.Rol", b =>
          {
            b.Navigation("RolPermisos");

            b.Navigation("Usuarios");
          });

      modelBuilder.Entity("TurneroApi.Models.Sector", b =>
          {
            b.Navigation("InversePadre");

            b.Navigation("MostradorSectores");

            b.Navigation("TicketsSectorIdActualNavigation");

            b.Navigation("TicketsSectorIdOrigenNavigation");
          });

      modelBuilder.Entity("TurneroApi.Models.Ticket", b =>
          {
            b.Navigation("Historiales");

            b.Navigation("Turnos");
          });

      modelBuilder.Entity("TurneroApi.Models.Turno", b =>
          {
            b.Navigation("Historiales");
          });

      modelBuilder.Entity("TurneroApi.Models.Usuario", b =>
          {
            b.Navigation("Historiales");

            b.Navigation("Puestos");
          });
#pragma warning restore 612, 618
    }
  }
}
